version: '3'
services:
  buildbot:
    hostname: docker
    container_name: buildbot
    build: ./
    volumes:
    - ./build:/var/lib/buildkite-agent/build/
    - ./ccache:/var/lib/buildkite-agent/ccache/
    - ./buildkite-agent.cfg:/buildkite/buildkite-agent.cfg
    environment:
    - BUILDKITE_AGENT_TOKEN=49847013e94f61ef546c9eaa4cd75e40f91ab3367c526e52a1
    restart: unless-stopped
